### ISSUE TITLE
[Suggestion]: Create optimization

### ISSUE THREAD

**Issue by GitJhopa** [CCr4ft3r/EnhancedBlockEntitiesReforged#12]
[crash-2023-06-26_23.37.11-client.txt](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11873923/crash-2023-06-26_23.37.11-client.txt)

**Comment by CCr4ft3r** [comment]
Please post your latest.log and a list of your installed mods.

**Comment by GitJhopa** [comment]
[latest.log](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11885913/latest.log)

**Comment by GitJhopa** [comment]
![image](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/assets/86250668/e95b97b0-ce73-45cd-8749-afb071349dbf)
![image](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/assets/86250668/641a619e-8d1a-4312-871b-a89ddd7c0ce5)
![image](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/assets/86250668/fc490558-b1da-4b3c-8202-89a8fe641750)

**Comment by CCr4ft3r** [comment]
You have BRRP 1.0.1 installed but you need 0.9.0

**Comment by GitJhopa** [comment]
wait

**Comment by GitJhopa** [comment]
Such a question, is it possible to fix the Create mod somehow? There, FPS suffers a lot because of the mechanisms, can you think of something?

**Comment by CCr4ft3r** [comment]
Is it because of Immediately fast or does it still happen without it? Which create blocks causing this fps drop?

**Comment by GitJhopa** [comment]
Hmm, didn't check. Check without Immediately fast?

**Comment by CCr4ft3r** [comment]
Yes

**Comment by GitJhopa** [comment]
Checked. FPS has gone down.

**Comment by GitJhopa** [comment]
I just noticed that the mechanisms and blocks from Create do not work with Entity Culling, they are visible even for 100+ blocks.

**Comment by GitJhopa** [comment]
https://spark.lucko.me/qfvEdabsKn spark client

**Comment by CCr4ft3r** [comment]
Ok, I will take s look into it and check if I can do anything about it. So your crash is gone by using the correct version?

**Comment by GitJhopa** [comment]
Thank you! YES!

**Comment by GitJhopa** [comment]
> Ok, I will take s look into it and check if I can do anything about it. So your crash is gone by using the correct version?

I really hope that YOU can, you will be the first to optimize this mod!

**Comment by GitJhopa** [comment]
To check, you can install the IDAS mod for Create, there are dungeons in them and you can check the FPS.

**Comment by CCr4ft3r** [comment]
This optimization would be best served in Create itself, since EBE focuses on vanilla block entities.
Someday, when I have more time again, I will check on it again and try to contribute to the original project.
