### ISSUE TITLE
[Suggestion] rework mod to use Forge API

### ISSUE THREAD

**Issue by ColonelGerdauf** [CCr4ft3r/EnhancedBlockEntitiesReforged#13]
It is generally optimal to use the Forge API in the long term. Reforgium was intended to make the job of porting easier, and Indium (what Reforgium is based on) was primarily made for compatibility between Sodium and a number of mods. The equivalent with Rubidium was not needed.

**Comment by CCr4ft3r** [comment]
Even if I can comprehend your argument, I don't consider it to be practical.
Reforgium is a library that provides rendering utility for other mods. 
Implementing the api in every mod that wants to utilize those optimized rendering methods would cause reduncancy, poorer maintainability and error-proneness.

**Comment by ColonelGerdauf** [comment]
While that may be true in theory... this is the only mod, asides from the authors own Connectedness, that makes any use of Reforgium let alone needs it. While it is fair to argue that the mod needs time to develop a portfolio, it has been about 8 months since release with not much bothering to even consider using the API.

In the world of coding and programming, it has been established to minimize the use of external APIs that is not your own. Not only will it introduce nightmares when updated, but it entices sloppy coding which will severely compromise code quality and performance.

I need to repeat that Reforgium is practically useless and completely pointless in the scope of (Neo)Forge.
