### ISSUE TITLE
[suggestion] enable external API access

### ISSUE THREAD

**Issue by ColonelGerdauf** [CCr4ft3r/EnhancedBlockEntitiesReforged#14]
Currently, to download EBE Reforged, you have to download directly from the CurseForge website. This is inconvenient for people who intend to download the mod through a Launcher such as Prism and MultiMC.

I am wondering if this is intentional on your part, because I was informed that the option to disallow external API's by default was sneakily enabled by the CF staff fairly recently.

**Comment by CCr4ft3r** [comment]
I enabled external API usage for all of my mods some time ago. It should work now
