### ISSUE TITLE
Incompatibility with Distant Horizons

### ISSUE THREAD

**Issue by unweeked** [CCr4ft3r/EnhancedBlockEntitiesReforged#15]
I tested the mod with Distant Horizons (I used the RC 2.0.0 available on their discord but I'm sure this also happens with older versions) and noticed that Block Entities (chests) rendered over the Distant Horizons blocks even when the Block Entities are behind. Is this an issue with Reforgium or is it on your side?
![2023-08-10_15 15 30](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/assets/96650761/4facb854-9da7-40d8-ad5e-0ff5f782b5c1)

**Comment by CCr4ft3r** [comment]
This was probably an issue of DH itself or another mod you have in your modpack. 
I'm using the following setup without problems:
Forge-1.19.2-43.3.2
DistantHorizons-2.0.0-a-RC4-1.19.2
EnhancedBlockEntities-Reforged-1.19.2-0.8.0
reforgium-1.0.12a

The second chest is three blocks south of the visible one under the earth block.
<img width="576" alt="ebe-distant-horizons" src="https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/assets/118105353/e8ca8748-4311-419c-80e7-d43a4d2a0e85">
