### ISSUE TITLE
[1.18.2] Joining into the world and the game crashed

### ISSUE THREAD

**Issue by Lxazl5770** [CCr4ft3r/EnhancedBlockEntitiesReforged#3]
The game crashed immediately when entering into the world.  

Description: Rendering Block Entity
java.lang.IllegalArgumentException: Cannot get property ...
[crash-2023-04-29_16.50.55-client.txt](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11358754/crash-2023-04-29_16.50.55-client.txt)

Dependency: BRRP 0.9.0 and Reforgium 1.0.12a

**Comment by CCr4ft3r** [comment]
Seems like an incompatibility with another mod of your modpack, since it works fine when only using EBE, BRRP and Reforgium. Please provide a minimal reproducable setup including the mods that triggering this isssue.

**Comment by Lxazl5770** [comment]
May incompatible with:
- Oh The Biomes You'll Go (byg)
- Architectury Lib
- Blueprint Lib

Removing byg causes the world won't load because of broken data packs, so I think this mod causes the problem.
[crash-2023-04-29_22.00.53-client.txt](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11359348/crash-2023-04-29_22.00.53-client.txt)

**Comment by Lxazl5770** [comment]
Plus, someone said that incompatibility happened in the resource pack that changes the texture of chests

**Comment by CCr4ft3r** [comment]
was an issue with wall signs. Is fixed in 0.7.3. Waiting for approve on CurseForge
