### ISSUE TITLE
[1.18.2] Client Crash on Start-up

### ISSUE THREAD

**Issue by Cixon** [CCr4ft3r/EnhancedBlockEntitiesReforged#8]
I assume there's a mod conflict...? Please help!

Crash Report:
[crash-2023-05-09_21.02.22-client.txt](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11437392/crash-2023-05-09_21.02.22-client.txt)

Log:
[latest.log](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11437396/latest.log)

Debug (just in-case):
[debug.log](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/11437398/debug.log)

**Comment by CCr4ft3r** [comment]
You need BRRP <= 0.9.0 , since there were a lot of restructuring in version 1.0.0. Hopefully I can update it soon, so EBE can use the latest version of BRRP.
